version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Add healthcheck to ensure the container is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: you can mount volumes for persistent data if needed
    # volumes:
    #   - ./data:/app/data